### ISSUE TITLE
Not pulling target from sensor

### ISSUE THREAD

**Issue by mikesumbler** [custom-components/climate.programmable_thermostat#43]
Hi,

Ended up using config.yaml to set parameters but I still can't get the thermostat to except the sensor target. 

===
climate:
    - platform: programmable_thermostat
      name: Central Heating Thermostat (VPT)
      heater: switch.thermostat_receiver
      actual_temp_sensor: sensor.battery_powered_wall_thermostat_air_temperature
      min_temp: 15
      max_temp: 25
      target_temp_sensor: sensor.battery_powered_wall_thermostat_set_point
      tolerance: 0.3
      hvac_options: 7
      auto_mode: all
      min_cycle_duration:
        minutes: 5
===
sensor.battery_powered_wall_thermostat_set_point is taken from a template as its contained in the state attributes of climate control (a HRT4ZW), i.e.

===
    - platform: template
      sensors:
        battery_powered_wall_thermostat_set_point:
          unit_of_measurement: '°C'
          friendly_name: "Central Heating Thermostat Setpoint"
          value_template: "{{ state_attr('climate.battery_powered_wall_thermostat', 'temperature') }}"

===

Want to use the thermostat to set the target and pass to the switch. The switch after an extension is out of the rannge of where the thermostat is so I use the controller as the bridge to it. 

Which logs do you need?

Thanks in advance

Mike

**Comment by mikesumbler** [comment]
Ah - sorry, as per Issue#23, you have to set to heat/cool mode. 

Thanks for a great app.

Cheers
Mike

**Comment by mdeweerd** [comment]
Hello

I noticed the same, the temperature is tracked only in auto mode, but not in heat mode.

In my [use case](https://community.home-assistant.io/t/generic-thermostat-extra-auxiliary-heater-with-setpoint-master-heater-1-c/357653), I would need tracking in Heat mode to allow using the same schedule (from the Scheduler component), to allow setting the HVAC mode in the same schedule.

It would be a nice to have if the HVAC mode could track another one in order to keep in sync with another climate module.

**Comment by mdeweerd** [comment]
If needed I'll create a separate case, but this seems related.

I have the thermostat set to auto mode and it isn't really heating.

![image](https://user-images.githubusercontent.com/1504752/142254928-b74f2b85-790e-497d-9240-67f25a896630.png)

```
- platform: programmable_thermostat
  name: 'Principal Aux'
  #heater: light.tz3000_5ng23zjs_ts0001_8d421efe_on_off
  heater:
    - switch.principal_aux_on_off
  actual_temp_sensor: sensor.principal_temperature
  target_temp_sensor: sensor.principal_aux_temperature
  min_temp: 7
  max_temp: 23
  #hvac_options: 3
  hvac_options: 5
  auto_mode: heating
  #ac_mode: false
  min_cycle_duration:
     seconds: 60
  tolerance: 0.2
  initial_hvac_mode: 'off'
```

I can switch on `switch.principal_aux_on_off` manually.
