### ISSUE TITLE
no heater activation

### ISSUE THREAD

**Issue by jump396** [custom-components/climate.programmable_thermostat#49]
hai all,
i've some problem with heater activation.
i tested the heater switch with generic_thermostat and it works well, but with this thermostat does nothing.

some ideas?

i tested only heater, i dont know if cooler part works proprely.

```
climate:
  - platform: programmable_thermostat
    name: termostato_pt_test
    heater: switch.swt_termostato_piano_terra_caldo
    cooler: switch.swt_termostato_piano_terra_freddo
    actual_temp_sensor: sensor.temp_termostato_piano_terra
    min_temp: 10
    max_temp: 30
    target_temp_sensor: sensor.target_temp_pt
    tolerance: 0.3
    hvac_options: 3
    min_cycle_duration:
      minutes: 1
```
 thks in advance
