### ISSUE TITLE
Same device for heater and cooler

### ISSUE THREAD

**Issue by grinco** [custom-components/climate.programmable_thermostat#63]
Hey there, for air-to-air heatpump users, it would be useful if we could use the same climate device for both heating and cooling the room. The only difference is climate operation mode. Tried adding the same climate device to both heating and cooling entities, and it only heats the room. 

Thanks for the great work!

**Comment by thefelixno** [comment]
Have you tried creating template-switches for your climate device?
That gives you two separate switches, which will act on the same climate device. One switch for heating, one for cooling.

Like this, to give you an idea:

```
switch:
  - platform: template
    switches:
      heatpump_heating:
        value_template: "{{ is_state_attr('climate.heatpump', 'hvac_action', 'heating') }}"
        turn_on:
          service: climate.set_hvac_mode
          target:
            entity_id: climate.heatpump
          data:
            hvac_mode: heat
        turn_off:
          service: climate.turn_off
          target:
            entity_id: climate.heatpump
      heatpump_cooling:
        value_template: "{{ is_state_attr('climate.heatpump', 'hvac_action', 'cooling') }}"
        turn_on:
          service: climate.set_hvac_mode
          target:
            entity_id: climate.heatpump
          data:
            hvac_mode: cool
        turn_off:
          service: climate.turn_off
          target:
            entity_id: climate.heatpump
```

https://www.home-assistant.io/integrations/switch.template/
