### ISSUE TITLE
Cooling doesn't turn off when idle

### ISSUE THREAD

**Issue by grinco** [custom-components/climate.programmable_thermostat#65]
When I set the thermostat to heat/cool and target temperature is reached it doesn't turn off the AC (even though the smart thermostat status shows off). If the AC is turned off manually, it won't start back until the temperature will go back up above the configured threshold (expected behavior).
![Screenshot_2023-06-04-21-55-54-99_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-components/climate.programmable_thermostat/assets/5553528/fa8a9e8a-68b7-4249-8c03-bbdc7e903095)

**Comment by wizardmelon** [comment]
Hi, I've got similar issue.

```
- platform: programmable_thermostat
  name: Sala
  heater: switch.heatvalve_sala 
  cooler: switch.hvac_sala
  actual_temp_sensor: sensor.temp_sala_offset
  min_temp: 17
  max_temp: 28
  target_temp_sensor: sensor.temp_target_sala
  tolerance: 0.3
  hvac_options: 3
  auto_mode: all
  min_cycle_duration:
    seconds: 1
```

When i turn set the thermostat "cool" the cooler switch turn on.
If I raise the target temperature, the cooler switch turn off.
But if the switch is on and I change the thermostat from "cool" to "off" the cooler switch remain on.
