### ISSUE TITLE
Component doesn't start anymore.

### ISSUE THREAD

**Issue by Stephan296** [custom-components/climate.programmable_thermostat#7]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/programmable_thermostat/climate.py", line 73, in async_setup_platform
    max_temp, target_entity_id, tolerance, initial_hvac_mode, unit)])
  File "/config/custom_components/programmable_thermostat/climate.py", line 95, in __init__
    self._target_temp = float(hass.states.get(target_entity_id).state)
ValueError: could not convert string to float: 'unknown'

**Comment by MapoDan** [comment]
Ciao,
are you sure that you target temperature sensor return a number value?
It seems that target entity_id state is unknown..

I'm using it and everything is fine..
Let me know. :)

**Comment by voltage84** [comment]
Same here :(

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/programmable_thermostat/climate.py", line 73, in async_setup_platform
    max_temp, target_entity_id, tolerance, initial_hvac_mode, unit)])
  File "/home/homeassistant/.homeassistant/custom_components/programmable_thermostat/climate.py", line 95, in __init__
    self._target_temp = float(hass.states.get(target_entity_id).state)
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by voltage84** [comment]
My content is like this: 21, 21, 21, 21, 21, 22, 22, ......... 21 168 values. No comma at the end.  Separator is comma + space just as in your example. Nevertheless it does not work without the spaces either. Same issue. Looks like the file is not even read.

**Comment by MapoDan** [comment]
Ciao,
mmh strange. I suppose that you are using the file_restore component, right?
The file's directory is whitelisted? If not you have to add this to your config:
```yaml
homeassistant:
  whitelist_external_dirs:
    - /config/local_file
```
Where /config/local_file is your directory where the file_restore component can find the file.

What you should have is:
- loaded the file_restore and programmable_thermostat in your custom_component folder (use HACS that will do it automatically and you can explore all custom integration as in a store)
- create a folder in under /config and whitelist this directory as above
- create a txt file in the folder above and valorize it with something like this:
14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.0, 19.0, 19.0, 19.5, 17.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.0, 19.0, 19.0, 19.5, 17.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.0, 19.0, 19.0, 19.5, 17.5, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.0, 19.0, 19.0, 19.5, 17.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.0, 19.0, 19.0, 19.5, 17.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.5, 19.0, 19.0, 19.0, 19.0, 19.0, 19.5, 19.5, 19.5, 19.5, 19.5, 19.0, 18.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 14.0, 18.5, 19.0, 19.0, 19.0, 19.0, 19.0, 19.5, 19.5, 19.5, 19.5, 19.5, 19.0, 18.0, 14.0
Close the data line with a new empty line.
Here an example that you can use to have a try. the first 2 lines are not mandatory, they are created automatically if you use the notify integration to store data in the file. This is not mandatory.
[room.txt](https://github.com/custom-components/climate.programmable_thermostat/files/3800319/room.txt)
- define the file_restore and programmable_thermostat as per documentation and restart hassio.

Let me know if you still have issue! ;)

**Comment by voltage84** [comment]
Hi!

Wow, thanks for the tips. Whitelisting is definitely missing, but
everything is under custom_components / file_restore and HA is the owner of
the dir. I will give this a try and let you know.

Best regards:

Viktor

MapoDan <notifications@github.com> (időpont: 2019. nov. 2., Szo, 10:41) ezt
írta:

**Comment by voltage84** [comment]
Hi!
I returned to this project recently. I updated both the programmable thermostat, and file restore to the latest version. I tried your suggestions. I used your room.txt. My config is as below:

configuration.yaml:
```
homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/custom_components/file_restore/

#Sensors
sensor:
  - platform: file_restore
    unit_of_measurement: '°C'
    file_path: /home/homeassistant/.homeassistant/custom_components/file_restore/room.txt
    name: file_restore
    length: week
    detail: hour
```
Error is the same:

Log Details (ERROR)
Sat Jan 04 2020 10:30:50 GMT+0100 (közép-európai téli idő)
Error while setting up platform programmable_thermostat
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/programmable_thermostat/climate.py", line 76, in async_setup_platform
    max_temp, target_entity_id, tolerance, initial_hvac_mode, unit, related_climate)])
  File "/home/homeassistant/.homeassistant/custom_components/programmable_thermostat/climate.py", line 99, in __init__
    self._target_temp = float(hass.states.get(target_entity_id).state)
AttributeError: 'NoneType' object has no attribute 'state'

No clues. :(

Best regards:

Viktor

**Comment by voltage84** [comment]
I use hassbian and not hass.io. But I do not think it should count.

**Comment by voltage84** [comment]
OK, I figured it out. Somehow.  Here is the end result. Thanks for your help.

[thermostat_program.txt](https://github.com/custom-components/climate.programmable_thermostat/files/4021753/thermostat_program.txt)



```
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/local_files

  - platform: programmable_thermostat
    name: groundfloor_heat
    heater: switch.pump3 #groundfloor floor pump
    cooler: switch.pump1 #groundfloor ceiling pump
    actual_temp_sensor: sensor.groundfloor_temperature
    min_temp: 18
    max_temp: 25
    target_temp_sensor: sensor.file_restore
    tolerance: 0.2

  - platform: file_restore
    unit_of_measurement: '°C'
    file_path: /home/homeassistant/.homeassistant/local_files/thermostat_program.txt
    name: file_restore
    length: week
    detail: hour

```
